/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.server;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Ordering;
import com.google.inject.Inject;
import io.airlift.resolver.ArtifactResolver;
import io.airlift.resolver.DefaultArtifact;
import io.trino.server.PluginManager.PluginsProvider;
import org.sonatype.aether.artifact.Artifact;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.Executor;
import java.util.function.Function;

import static com.google.common.collect.ImmutableList.toImmutableList;
import static io.trino.server.PluginDiscovery.addPluginServices;
import static io.trino.util.Executors.executeUntilFailure;
import static java.util.Objects.requireNonNull;

public class DevelopmentPluginsProvider
        implements PluginsProvider
{
    private final ArtifactResolver resolver;
    private final List<String> plugins;
    private final Executor executor;

    @Inject
    public DevelopmentPluginsProvider(DevelopmentLoaderConfig config, @ForStartup Executor executor)
    {
        this.resolver = new ArtifactResolver(config.getMavenLocalRepository(), config.getMavenRemoteRepository());
        this.plugins = ImmutableList.copyOf(config.getPlugins());
        this.executor = requireNonNull(executor, "executor is null");
    }

    @Override
    public void loadPlugins(Loader loader, ClassLoaderFactory createClassLoader)
    {
        executeUntilFailure(
                executor,
                plugins.stream()
                        .map(plugin -> (Callable<?>) () -> {
                            loader.load(plugin, () -> buildClassLoader(plugin, createClassLoader));
                            return null;
                        })
                        .collect(toImmutableList()));
    }

    private PluginClassLoader buildClassLoader(String plugin, ClassLoaderFactory classLoaderFactory)
    {
        try {
            return doBuildClassLoader(plugin, urls -> classLoaderFactory.create(plugin, urls));
        }
        catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private PluginClassLoader doBuildClassLoader(String plugin, Function<List<URL>, PluginClassLoader> classLoaderFactory)
            throws IOException
    {
        File file = new File(plugin);
        if (file.isFile() && (file.getName().equals("pom.xml") || file.getName().endsWith(".pom"))) {
            return buildClassLoaderFromPom(file, classLoaderFactory);
        }
        else if (file.isDirectory()) {
            return buildClassLoaderFromPluginDirectory(file, classLoaderFactory);
        }

        return buildClassLoaderFromCoordinates(plugin, classLoaderFactory);
    }

    private PluginClassLoader buildClassLoaderFromPom(File pomFile, Function<List<URL>, PluginClassLoader> classLoaderFactory)
            throws IOException
    {
        List<Artifact> artifacts = resolver.resolvePom(pomFile);
        PluginClassLoader classLoader = createClassLoader(artifacts, classLoaderFactory);

        Artifact artifact = artifacts.get(0);
        if (!artifact.getExtension().equals("trino-plugin")) {
            throw new RuntimeException("Unexpected extension for main artifact: " + artifact);
        }
        File artifactFile = artifact.getFile();

        return addPluginServices(artifactFile, artifactFile.getParentFile().getCanonicalFile(), classLoader);
    }

    private PluginClassLoader buildClassLoaderFromCoordinates(String coordinates, Function<List<URL>, PluginClassLoader> classLoaderFactory)
            throws IOException
    {
        Artifact rootArtifact = new DefaultArtifact(coordinates);
        List<Artifact> artifacts = resolver.resolveArtifacts(rootArtifact);
        return createClassLoader(artifacts, classLoaderFactory);
    }

    private PluginClassLoader buildClassLoaderFromPluginDirectory(File dir, Function<List<URL>, PluginClassLoader> classLoaderFactory)
            throws IOException
    {
        // classpath.txt is generated by maven-dependency-plugin dependency:build-classpath
        Path classpathFile = Path.of(dir.getAbsolutePath(), "target", "classpath.txt");
        if (!classpathFile.toFile().exists()) {
            throw new RuntimeException("Could not find plugin classpath file at: %s".formatted(classpathFile));
        }

        Path targetDir = Path.of(dir.getAbsolutePath(), "target");
        Path classesDir = targetDir.resolve("classes");
        if (!classesDir.toFile().exists()) {
            throw new RuntimeException("Could not find plugin classes path at: %s".formatted(classesDir));
        }

        // read all entries from classpath.txt
        ImmutableList<URL> dependencies = Files.readAllLines(classpathFile)
                .stream()
                .flatMap(l -> Arrays.stream(l.split(":")))
                .map(path -> {
                    try {
                        return new File(path).toURI().toURL();
                    }
                    catch (MalformedURLException e) {
                        throw new RuntimeException(e);
                    }
                })
                .collect(toImmutableList());

        ImmutableList<URL> urls = ImmutableList.<URL>builder()
                .add(classesDir.toUri().toURL())
                .addAll(dependencies)
                .build();

        PluginClassLoader classLoader = classLoaderFactory.apply(urls);

        return addPluginServices(classesDir.toFile(), targetDir.toFile(), classLoader);
    }

    private static PluginClassLoader createClassLoader(List<Artifact> artifacts, Function<List<URL>, PluginClassLoader> classLoaderFactory)
            throws IOException
    {
        List<URL> urls = new ArrayList<>();
        for (Artifact artifact : sortedArtifacts(artifacts)) {
            if (artifact.getFile() == null) {
                throw new RuntimeException("Could not resolve artifact: " + artifact);
            }
            File file = artifact.getFile().getCanonicalFile();
            urls.add(file.toURI().toURL());
        }
        return classLoaderFactory.apply(urls);
    }

    private static List<Artifact> sortedArtifacts(List<Artifact> artifacts)
    {
        List<Artifact> list = new ArrayList<>(artifacts);
        list.sort(Ordering.natural().nullsLast().onResultOf(Artifact::getFile));
        return list;
    }
}
